export const GET_LIST_OF_VEHICLES = 'GET_LIST_OF_VEHICLES';
export const VEHICLE_LIST_FETCH_ERROR = 'VEHICLE_LIST_FETCH_ERROR';
export const GET_LIST_OF_VEHICLES_FILTERS = 'GET_LIST_OF_VEHICLES_FILTERS';
export const UPDATE_VECHILES_LOAD_STATUS = 'UPDATE_VECHILES_LOAD_STATUS';
